/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.form;

import javax.swing.JFrame;
import silab.sd.personapp.view.component.InputPanelAddPerson;

/**
 *
 * @author sicov
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       //jpanelPerson.setVisible(false);
       inputAddPerson.setVisible(false);
    }
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputAddPerson = new silab.sd.personapp.view.component.InputPanelAddPerson();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuConfiguration = new javax.swing.JMenu();
        jmenuPerson = new javax.swing.JMenu();
        jmiAddPerson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmenuConfiguration.setText("Configuration");
        jMenuBar1.add(jmenuConfiguration);

        jmenuPerson.setText("Person");

        jmiAddPerson.setText("add");
        jmiAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddPersonActionPerformed(evt);
            }
        });
        jmenuPerson.add(jmiAddPerson);

        jMenuBar1.add(jmenuPerson);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddPersonActionPerformed
       inputAddPerson.setVisible(true);
       
    }//GEN-LAST:event_jmiAddPersonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private silab.sd.personapp.view.component.InputPanelAddPerson inputAddPerson;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmenuConfiguration;
    private javax.swing.JMenu jmenuPerson;
    private javax.swing.JMenuItem jmiAddPerson;
    // End of variables declaration//GEN-END:variables
}
