/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.form;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import silab.sd.personapp.view.component.validator.impl.RequiredStringValidator;

/**
 *
 * @author laptop-02
 */
public class FrmPersonComponent extends javax.swing.JDialog {

    /**
     * Creates new form FrmPersonComponent
     */
    public FrmPersonComponent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        prepareComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        inputFirstname = new silab.sd.personapp.view.component.InputTextfieldPanel();
        inputLastname = new silab.sd.personapp.view.component.InputTextfieldPanel();
        inputGender = new silab.sd.personapp.view.component.InputComboPanel();
        inputBirthday = new silab.sd.personapp.view.component.InputDateSepareteElements();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //uzmi vrednost za ime
        //inputFirstname.getLblErrorValue().setText("");
     
        try{
            String firstname = inputFirstname.getValue().toString();
            
            JOptionPane.showMessageDialog(this, "Ime: " + firstname);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Validacija nije prosla.");
        }
        
         try{
            String lastname = inputLastname.getValue().toString();
            
            JOptionPane.showMessageDialog(this, "Prezime: " + lastname);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Validacija nije prosla.");
        }
        
        try {
            String gender = inputGender.getValue().toString();
            JOptionPane.showMessageDialog(this, "Pol: " + gender);
        } catch (Exception ex) {
            Logger.getLogger(FrmPersonComponent.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        try {
            Date birthDay = (Date) inputBirthday.getValue();
            JOptionPane.showMessageDialog(this, "Datum rodjenja: " + new SimpleDateFormat("dd.mm.yyyy.").format(birthDay));
        } catch (Exception ex) {
            Logger.getLogger(FrmPersonComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
        
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private silab.sd.personapp.view.component.InputDateSepareteElements inputBirthday;
    private silab.sd.personapp.view.component.InputTextfieldPanel inputFirstname;
    private silab.sd.personapp.view.component.InputComboPanel inputGender;
    private silab.sd.personapp.view.component.InputTextfieldPanel inputLastname;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        inputFirstname.setValidator(new RequiredStringValidator());
        inputFirstname.getLblText().setText("Firstname:");
        inputFirstname.getLblErrorValue().setText("");
        
        inputLastname.setValidator(new RequiredStringValidator());
        inputLastname.getLblText().setText("Lastname:");
        inputLastname.getLblErrorValue().setText("");
        
        inputGender.getLblText().setText("Gender:");
        inputGender.getLblErrorValue().setText("");
        
        inputGender.getCbValue().removeAllItems();
        /*
        inputGender.getCbValue().addItem("Male");
        inputGender.getCbValue().addItem("Female");
        */
        List<String> genders = new ArrayList<String>(){
            {
                add("Male");
                add("Female");
            }
        };
        inputGender.getCbValue().setModel(new DefaultComboBoxModel<>(genders.toArray()));
        
        inputBirthday.getLblText().setText("Birthday:");
        inputBirthday.getLblErrorValue().setText("");
        
        
        
    }
}
