/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.component;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import silab.sd.personapp.view.component.validator.impl.RequiredStringValidator;
import silab.sd.personapp.view.form.FrmPersonComponent;

/**
 *
 * @author sicov
 */
public class InputPanelAddPerson extends javax.swing.JPanel {

    /**
     * Creates new form InputPanelAddPerson
     */
    public InputPanelAddPerson() {
        initComponents();
        prepareComponents();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddPerson = new javax.swing.JButton();
        inputFirstname = new silab.sd.personapp.view.component.InputTextfieldPanel();
        inputLastname = new silab.sd.personapp.view.component.InputTextfieldPanel();
        inputGender = new silab.sd.personapp.view.component.InputComboPanel();
        inputDate = new silab.sd.personapp.view.component.InputDateSepareteElements();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add Person"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddPerson.setText("Add");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });
        add(btnAddPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 328, -1, -1));
        add(inputFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 38, -1, -1));
        add(inputLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 107, -1, -1));
        add(inputGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        add(inputDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        try{
            String firstname = inputFirstname.getValue().toString();
            
            JOptionPane.showMessageDialog(this, "Ime: " + firstname);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Validacija nije prosla.");
        }
        
         try{
            String lastname = inputLastname.getValue().toString();
            
            JOptionPane.showMessageDialog(this, "Prezime: " + lastname);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Validacija nije prosla.");
        }
        
        try {
            String gender = inputGender.getValue().toString();
            JOptionPane.showMessageDialog(this, "Pol: " + gender);
        } catch (Exception ex) {
            Logger.getLogger(FrmPersonComponent.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        try {
            Date birthDay = (Date) inputDate.getValue();
            JOptionPane.showMessageDialog(this, "Datum rodjenja: " + new SimpleDateFormat("dd.mm.yyyy.").format(birthDay));
        } catch (Exception ex) {
            Logger.getLogger(FrmPersonComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private silab.sd.personapp.view.component.InputDateSepareteElements inputDate;
    private silab.sd.personapp.view.component.InputTextfieldPanel inputFirstname;
    private silab.sd.personapp.view.component.InputComboPanel inputGender;
    private silab.sd.personapp.view.component.InputTextfieldPanel inputLastname;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        inputFirstname.setValidator(new RequiredStringValidator());
        inputFirstname.getLblText().setText("Firstname:");
        inputFirstname.getLblErrorValue().setText("");
        
        inputLastname.setValidator(new RequiredStringValidator());
        inputLastname.getLblText().setText("Lastname:");
        inputLastname.getLblErrorValue().setText("");
        
        inputGender.getLblText().setText("Gender:");
        inputGender.getLblErrorValue().setText("");
        
        inputGender.getCbValue().removeAllItems();
        
        List<String> genders = new ArrayList<String>(){
            {
                add("Male");
                add("Female");
            }
        };
        inputGender.getCbValue().setModel(new DefaultComboBoxModel<>(genders.toArray()));
        
        inputDate.getLblText().setText("Birthday:");
        inputDate.getLblErrorValue().setText("");
        
        
    }
}
