/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.component;

import java.text.SimpleDateFormat;

/**
 *
 * @author laptop-02
 */
public class InputDateSepareteElements extends javax.swing.JPanel implements GetValue{

    /**
     * Creates new form InputDateSepareteElements
     */
    public InputDateSepareteElements() {
        initComponents();
        prepareComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        cbDay = new javax.swing.JComboBox<>();
        cbMounth = new javax.swing.JComboBox<>();
        lblErrorValue = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 0, 0));

        lblText.setText("jLabel1");

        lblErrorValue.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorValue.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDay, 0, 41, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cbMounth, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMounth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Integer> cbDay;
    private javax.swing.JComboBox<Integer> cbMounth;
    private javax.swing.JComboBox<Integer> cbYear;
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<Integer> getCbDay() {
        return cbDay;
    }

    public javax.swing.JComboBox<Integer> getCbMounth() {
        return cbMounth;
    }

    public javax.swing.JComboBox<Integer> getCbYear() {
        return cbYear;
    }

    public javax.swing.JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public javax.swing.JLabel getLblText() {
        return lblText;
    }

    private void prepareComponent() {
        for (int i = 1; i <= 31; i++) {
            cbDay.addItem(i);
        }
        
        for (int i = 1; i <= 12; i++) {
            cbMounth.addItem(i);
        }
        
        for (int i = 1900; i <= 2021; i++) {
            cbYear.addItem(i);
        }
    }

    @Override
    public Object getValue() throws Exception {
        SimpleDateFormat sdf = new SimpleDateFormat("d.m.yyyy.");
        return sdf.parse(cbDay.getSelectedItem()+"."+cbMounth.getSelectedItem()+"." + cbYear.getSelectedItem()+".");
    }
}
